/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.Employee_Phones;
import company.TheTools;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.print.attribute.standard.MediaPrintableArea.MM;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author framawy
 */
public class EmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeForm
     */
    public EmployeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNum = new Controls.JTextBox(15);
        txtName = new Controls.JTextBox(15);
        txtSalary = new Controls.JTextBox(15);
        bdnupdate = new Controls.JMyButton();
        bdndelete = new Controls.JMyButton();
        pdnfind = new Controls.JMyButton();
        bdnall = new Controls.JMyButton();
        bdnclear = new Controls.JMyButton();
        bdnback = new Controls.JMyButton();
        bdnadd = new Controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable2 = new javax.swing.JTable();
        rdoNum = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        rdoAddress = new javax.swing.JRadioButton();
        txtSearch = new Controls.JTextBox(15);
        bdnSearch = new Controls.JMyButton();
        jLabel2 = new javax.swing.JLabel();
        txtaddress = new Controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbd = new com.toedter.calendar.JDateChooser();
        jbh = new com.toedter.calendar.JDateChooser();
        rdoHD = new javax.swing.JRadioButton();
        rdoSalary = new javax.swing.JRadioButton();
        rdoBD = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        combo = new Controls.JMyCombo();
        jMyButton1 = new Controls.JMyButton();
        rdodept = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtphone = new Controls.JTextBox(15);
        phoneadd = new Controls.JMyButton();
        bdnremove = new Controls.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblphone = new javax.swing.JTable();
        Phone = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employee Form");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address");

        txtNum.setEditable(false);
        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        bdnupdate.setText("Update");
        bdnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnupdateActionPerformed(evt);
            }
        });

        bdndelete.setText("Delete");
        bdndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdndeleteActionPerformed(evt);
            }
        });

        pdnfind.setText("Find");
        pdnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdnfindActionPerformed(evt);
            }
        });

        bdnall.setText("All");
        bdnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnallActionPerformed(evt);
            }
        });

        bdnclear.setText("Clear");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        bdnback.setText("Back");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        bdnadd.setText("Add");
        bdnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnaddActionPerformed(evt);
            }
        });

        tblTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Salary", "address", "Hiring Date", "Birth Date", "Deptno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable2);

        rdoNum.setSelected(true);
        rdoNum.setText("Number");
        rdoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumActionPerformed(evt);
            }
        });

        rdoName.setText("Name");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });

        rdoAddress.setText("Address");
        rdoAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAddressActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        bdnSearch.setText("Search");
        bdnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Search By");

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Salary");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("BD");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("HD");

        rdoHD.setText("Hiring Date");

        rdoSalary.setText("Salary");

        rdoBD.setText("BirthDate");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dept Num");

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jMyButton1.setText(".");
        jMyButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton1ActionPerformed(evt);
            }
        });

        rdodept.setText("Deptno");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Phone");

        phoneadd.setText("Add");
        phoneadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneaddActionPerformed(evt);
            }
        });

        bdnremove.setText("Remove");
        bdnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnremoveActionPerformed(evt);
            }
        });

        tblphone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numbers"
            }
        ));
        jScrollPane2.setViewportView(tblphone);

        Phone.setText("Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtphone)
                                .addGap(34, 34, 34)
                                .addComponent(phoneadd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bdnremove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pdnfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSalary)
                                            .addComponent(txtName)
                                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(155, 155, 155)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoSalary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoBD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoHD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdodept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Phone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bdnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5))
                            .addComponent(txtNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pdnfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnremove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNum)
                            .addComponent(rdoName)
                            .addComponent(rdoAddress)
                            .addComponent(jLabel2)
                            .addComponent(rdoSalary)
                            .addComponent(rdoBD)
                            .addComponent(rdoHD)
                            .addComponent(rdodept)
                            .addComponent(Phone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNameActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        this.dispose();
        TheTools.OpenForm(new FrmMain());
    }//GEN-LAST:event_bdnbackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnGroup2.add(rdoNum);
        btnGroup2.add(rdoName);
        btnGroup2.add(rdoAddress);
        btnGroup2.add(rdoSalary);
        btnGroup2.add(rdoBD);
        btnGroup2.add(rdoBD);
        btnGroup2.add(rdoHD);
        btnGroup2.add(rdodept);
        btnGroup2.add(Phone);
        ClearData();
tblTable2.getTableHeader().setReorderingAllowed(false);
tblphone.getTableHeader().setReorderingAllowed(false);
 db.go.fillComboBox("department", "DeptName", combo);
 emp.getAllRows(tblTable2);
 txtSearch.setText("0");
   


 
    }//GEN-LAST:event_formWindowOpened

    private void rdoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumActionPerformed
 
    Employee emp = new Employee();
        Department dept = new Department();

    private void rdoAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAddressActionPerformed

    private void ClearData(){
        
        TheTools.clearText(this);
        txtNum.setText(emp.getAutoNumber());
        bdnadd.setEnabled(true);
        bdnupdate.setEnabled(false);
        bdndelete.setEnabled(false);
       bdnremoveActionPerformed(null);
        txtName.requestFocus();
        txtSearch.setText("0");
        
        
    }
    
    
    
    
    
    
    
    
    private void SetValue(){
         try{
    emp.setEmpNo(Integer.parseInt(txtNum.getText()));
    emp.setEmpName(txtName.getText());
    emp.setAdress(txtaddress.getText());
    emp.setSalary(Double.valueOf(txtSalary.getText()));
    
    //Date
   SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
   String HDate = String.valueOf(f.format(jbh.getDate()));
   String BDate = String.valueOf(f.format(jbd.getDate()));
   emp.setHiringDate(HDate);
   emp.setBirthDate(BDate);
   ///Connect the forigen Key
   String dName =combo.getSelectedItem().toString();
   String dNo = dept.getValueByname(dName);
   emp.setDeptNo(Integer.parseInt(dNo));
         }
          catch(Exception ex){
          TheTools.msgBox(ex.getMessage());
      }
}
    Employee_Phones  phone = new Employee_Phones();
    private void bdnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnaddActionPerformed
        SetValue();
        emp.add();
        //Add Phones
        phone.setEmpNo(Integer.parseInt(txtNum.getText()));
        
        for(int x = 0 ; x < tblphone.getRowCount() ; x++) {
            
            phone.setPhone((String)tblphone.getValueAt(x, 0));
            phone.add();
        }
        
        
        ClearData();
       emp.getAllRows(tblTable2);
        
        
    }//GEN-LAST:event_bdnaddActionPerformed

    private void jMyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton1ActionPerformed
        int DeptNo = Integer.parseInt(dept.getAutoNumber());
        String DeptName = JOptionPane.showInputDialog("Enter Name ", null);
        String Location =  JOptionPane.showInputDialog("Enter Location ", null);
        
        dept.setDeptNo(DeptNo);
        dept.setDeptName(DeptName);
        dept.setLocation(Location);
        dept.add();
        
        db.go.fillComboBox("department", "DeptName", combo);
    }//GEN-LAST:event_jMyButton1ActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        ClearData();
         emp.getAllRows(tblTable2);
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnupdateActionPerformed
        SetValue();
        emp.update();
        
        
        
        phone.setEmpNo(Integer.parseInt(txtNum.getText()));
        
        //delete Phones
        phone.deletebyEmp();
        //Add Phones
        for(int x = 0 ; x < tblphone.getRowCount() ; x++) {
            
            phone.setPhone((String)tblphone.getValueAt(x, 0));
            phone.add();
        }

        ClearData();
        emp.getAllRows(tblTable2);
    }//GEN-LAST:event_bdnupdateActionPerformed

    private void bdndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdndeleteActionPerformed
    if(TheTools.confirmMsg("Do you want to delete")){
        
        
        
        phone.setEmpNo(Integer.parseInt(txtNum.getText()));
        
        //delete Phones
        phone.deletebyEmp();
        
        //delete Emp
        SetValue();
        emp.delete();
        //Add Phones
        for(int x = 0 ; x < tblphone.getRowCount() ; x++) {
            
            phone.setPhone((String)tblphone.getValueAt(x, 0));
            phone.add();
        }
        ClearData();
        emp.getAllRows(tblTable2);
    }
    }//GEN-LAST:event_bdndeleteActionPerformed

    private void pdnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdnfindActionPerformed
        try{
        String Empno = JOptionPane.showInputDialog("Enter Number", null);
        int ENO = Integer.parseInt(Empno);
        emp.setEmpNo(ENO);
        emp.getOneRow(tblTable2);
        }
         catch(Exception ex){
          TheTools.msgBox(ex.getMessage());
      }
    }//GEN-LAST:event_pdnfindActionPerformed

    private void bdnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnallActionPerformed
        emp.getAllRows(tblTable2);
    }//GEN-LAST:event_bdnallActionPerformed

    private void tblTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTable2MouseClicked
        try{
            
            int row = tblTable2.getSelectedRow();
            
            txtNum.setText((String)tblTable2.getValueAt(row, 0));
            txtName.setText((String)tblTable2.getValueAt(row, 1));
            txtSalary.setText((String)tblTable2.getValueAt(row,2));
          txtaddress.setText((String)tblTable2.getValueAt(row, 3));
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          Date dateH = sdf.parse((String)tblTable2.getValueAt(row, 4));
          Date dateB = sdf.parse(tblTable2.getValueAt(row, 5).toString());
          jbh.setDate(dateH);
          jbd.setDate(dateB);
          combo.setSelectedItem(tblTable2.getValueAt(row, 6));
           phone.setEmpNo(Integer.parseInt(txtNum.getText()));
           phone.getAllRows(tblphone);

            bdnadd.setEnabled(false);
            bdnupdate.setEnabled(true);
            bdndelete.setEnabled(true);
            
        }
        catch(Exception ex){
            
            TheTools.msgBox(ex.getMessage());
            
        }
    }//GEN-LAST:event_tblTable2MouseClicked

    private String getMyLike(){
        
        return " like'%" + txtSearch.getText() + "%'";
    }
    private void bdnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnSearchActionPerformed
            try{
        String strSearch = "select * from employee where ";
        if(rdoNum.isSelected()){
            strSearch += " EmpNo " + getMyLike();
        }
        else if(rdoName.isSelected()){
            strSearch += " EmpName " + getMyLike();
            
        }
         else if(rdoSalary.isSelected()){
            strSearch += " Salary " + getMyLike();
            
        }
         else if(rdoAddress.isSelected()){
            strSearch += " Adress " + getMyLike();
            
        }
         else if(rdoBD.isSelected()){
            strSearch += " BirthDate " + getMyLike();
            
        }
         else if(rdoHD.isSelected()){
            strSearch += " HiringDate " + getMyLike();
            
        }
         else if (rdodept.isSelected()){
             strSearch += "DeptNo " + getMyLike();
         }
             else {
                     String strEmpNum = phone.getEmpNoByPhone(txtSearch.getText());
                      strSearch += " EmpNo like'%" +  strEmpNum + "%'";
                     }
         
        emp.getCustomRows(strSearch, tblTable2);
        }
        catch(Exception ex){
            TheTools.msgBox(ex.getMessage());
        }
        
    }//GEN-LAST:event_bdnSearchActionPerformed

    private void bdnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnremoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblphone.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_bdnremoveActionPerformed

    private void phoneaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneaddActionPerformed
        DefaultTableModel model =(DefaultTableModel) tblphone.getModel();
        model.addRow(new Object[]{txtphone.getText()});
        txtphone.setText("");
        txtphone.requestFocus();
    }//GEN-LAST:event_phoneaddActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Phone;
    private Controls.JMyButton bdnSearch;
    private Controls.JMyButton bdnadd;
    private Controls.JMyButton bdnall;
    private Controls.JMyButton bdnback;
    private Controls.JMyButton bdnclear;
    private Controls.JMyButton bdndelete;
    private Controls.JMyButton bdnremove;
    private Controls.JMyButton bdnupdate;
    private javax.swing.ButtonGroup btnGroup2;
    private Controls.JMyCombo combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Controls.JMyButton jMyButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jbd;
    private com.toedter.calendar.JDateChooser jbh;
    private Controls.JMyButton pdnfind;
    private Controls.JMyButton phoneadd;
    private javax.swing.JRadioButton rdoAddress;
    private javax.swing.JRadioButton rdoBD;
    private javax.swing.JRadioButton rdoHD;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNum;
    private javax.swing.JRadioButton rdoSalary;
    private javax.swing.JRadioButton rdodept;
    private javax.swing.JTable tblTable2;
    private javax.swing.JTable tblphone;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
